Repository kubernetes-sigs/sig-multicluster-site, pull requests merged in 2025-02, with the labels that each got.

#36 Add Cilium to MCS-API implementations
  site-src/guides/index.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#35 add KEP links to home page
  site-src/index.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#28 Fix Work API example implementation OCM-io doc URL
  site-src/concepts/work-api.md
Labels: approved, lgtm, cncf-cla: yes, size/XS

#26 yaml formatting & indentation
  site-src/api-types/cluster-set.md
  site-src/concepts/about-api.md
  site-src/concepts/cluster-profile-api.md
  site-src/concepts/work-api.md
  site-src/guides/coredns.md
Labels: approved, lgtm, size/L, cncf-cla: yes

#30 Adjust the README to better reflect the SIG-MC community.
  README.md
Labels: approved, lgtm, cncf-cla: yes, size/XS
